[2025-05-06T18:39:44.014+0000] {processor.py:154} INFO - Started process (PID=82801) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:39:44.014+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:39:44.015+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:39:44.015+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:39:44.017+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:39:44.016+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:39:44.017+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:39:44.028+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.017 seconds
[2025-05-06T18:40:14.714+0000] {processor.py:154} INFO - Started process (PID=82867) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:40:14.715+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:40:14.716+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:40:14.715+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:40:14.717+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:40:14.717+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:40:14.718+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:40:14.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.020 seconds
[2025-05-06T18:40:45.575+0000] {processor.py:154} INFO - Started process (PID=82933) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:40:45.576+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:40:45.576+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:40:45.576+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:40:45.578+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:40:45.578+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:40:45.579+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:40:45.590+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.017 seconds
[2025-05-06T18:41:16.370+0000] {processor.py:154} INFO - Started process (PID=83000) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:41:16.370+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:41:16.371+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:41:16.371+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:41:16.374+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:41:16.373+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:41:16.375+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:41:16.390+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.023 seconds
[2025-05-06T18:41:47.004+0000] {processor.py:154} INFO - Started process (PID=83065) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:41:47.004+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:41:47.005+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:41:47.005+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:41:47.008+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:41:47.007+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:41:47.008+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:41:47.023+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.022 seconds
[2025-05-06T18:42:17.746+0000] {processor.py:154} INFO - Started process (PID=83131) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:42:17.747+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:42:17.747+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:42:17.747+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:42:17.749+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:42:17.748+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:42:17.749+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:42:17.758+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:42:48.554+0000] {processor.py:154} INFO - Started process (PID=83197) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:42:48.555+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:42:48.555+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:42:48.555+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:42:48.559+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:42:48.558+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:42:48.559+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:42:48.573+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.024 seconds
[2025-05-06T18:43:19.302+0000] {processor.py:154} INFO - Started process (PID=83263) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:43:19.303+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:43:19.304+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:43:19.304+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:43:19.307+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:43:19.306+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:43:19.307+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:43:19.321+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.022 seconds
[2025-05-06T18:43:49.959+0000] {processor.py:154} INFO - Started process (PID=83329) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:43:49.960+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:43:49.960+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:43:49.960+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:43:49.962+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:43:49.961+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:43:49.962+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:43:49.976+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.018 seconds
[2025-05-06T18:44:20.692+0000] {processor.py:154} INFO - Started process (PID=83394) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:44:20.692+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:44:20.692+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:44:20.692+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:44:20.694+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:44:20.694+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:44:20.694+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:44:20.703+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.012 seconds
[2025-05-06T18:44:51.487+0000] {processor.py:154} INFO - Started process (PID=83450) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:44:51.487+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:44:51.488+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:44:51.488+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:44:51.491+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:44:51.490+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:44:51.491+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:44:51.503+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.020 seconds
[2025-05-06T18:45:22.195+0000] {processor.py:154} INFO - Started process (PID=83516) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:45:22.196+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:45:22.196+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:45:22.196+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:45:22.199+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:45:22.198+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:45:22.199+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:45:22.214+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.022 seconds
[2025-05-06T18:45:53.015+0000] {processor.py:154} INFO - Started process (PID=83582) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:45:53.015+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:45:53.016+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:45:53.016+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:45:53.018+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:45:53.017+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:45:53.018+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:45:53.028+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.015 seconds
[2025-05-06T18:46:23.719+0000] {processor.py:154} INFO - Started process (PID=83648) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:46:23.719+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:46:23.720+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:46:23.719+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:46:23.722+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:46:23.721+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:46:23.722+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:46:23.733+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.016 seconds
[2025-05-06T18:46:54.491+0000] {processor.py:154} INFO - Started process (PID=83714) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:46:54.492+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:46:54.493+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:46:54.493+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:46:54.496+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:46:54.495+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:46:54.496+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:46:54.514+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.025 seconds
[2025-05-06T18:47:25.379+0000] {processor.py:154} INFO - Started process (PID=83780) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:47:25.380+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:47:25.380+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:47:25.380+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:47:25.382+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:47:25.382+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:47:25.382+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:47:25.392+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:47:56.077+0000] {processor.py:154} INFO - Started process (PID=83844) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:47:56.078+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:47:56.079+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:47:56.078+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:47:56.082+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:47:56.081+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:47:56.082+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:47:56.094+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.019 seconds
[2025-05-06T18:48:26.752+0000] {processor.py:154} INFO - Started process (PID=83910) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:48:26.753+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:48:26.753+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:48:26.753+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:48:26.755+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:48:26.754+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:48:26.755+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:48:26.763+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.012 seconds
[2025-05-06T18:48:57.409+0000] {processor.py:154} INFO - Started process (PID=83976) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:48:57.410+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:48:57.410+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:48:57.410+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:48:57.413+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:48:57.412+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:48:57.413+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:48:57.426+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.020 seconds
[2025-05-06T18:49:28.193+0000] {processor.py:154} INFO - Started process (PID=84042) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:49:28.193+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:49:28.193+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:49:28.193+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:49:28.195+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:49:28.195+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:49:28.195+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:49:28.205+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.015 seconds
[2025-05-06T18:49:58.998+0000] {processor.py:154} INFO - Started process (PID=84108) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:49:58.999+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:49:59.000+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:49:59.000+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:49:59.003+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:49:59.003+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:49:59.003+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:49:59.018+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.022 seconds
[2025-05-06T18:50:29.519+0000] {processor.py:154} INFO - Started process (PID=84165) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:50:29.520+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:50:29.520+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:50:29.520+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:50:29.523+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:50:29.522+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:50:29.524+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:50:29.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.020 seconds
[2025-05-06T18:51:00.262+0000] {processor.py:154} INFO - Started process (PID=84231) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:51:00.262+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:51:00.263+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:51:00.263+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:51:00.266+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:51:00.265+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:51:00.266+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:51:00.280+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.022 seconds
[2025-05-06T18:51:31.042+0000] {processor.py:154} INFO - Started process (PID=84297) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:51:31.042+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:51:31.043+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:51:31.043+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:51:31.047+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:51:31.045+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:51:31.047+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:51:31.062+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.024 seconds
[2025-05-06T18:52:01.871+0000] {processor.py:154} INFO - Started process (PID=84363) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:52:01.872+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:52:01.872+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:52:01.872+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:52:01.874+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:52:01.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:52:01.874+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:52:01.885+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.016 seconds
[2025-05-06T18:52:32.639+0000] {processor.py:154} INFO - Started process (PID=84429) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:52:32.639+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:52:32.640+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:52:32.640+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:52:32.641+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:52:32.641+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:52:32.641+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:52:32.651+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:53:03.363+0000] {processor.py:154} INFO - Started process (PID=84495) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:53:03.363+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:53:03.364+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:53:03.364+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:53:03.366+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:53:03.365+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:53:03.366+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:53:03.378+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.017 seconds
[2025-05-06T18:53:34.092+0000] {processor.py:154} INFO - Started process (PID=84561) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:53:34.093+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:53:34.093+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:53:34.093+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:53:34.096+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:53:34.095+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:53:34.096+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:53:34.108+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.017 seconds
[2025-05-06T18:54:04.852+0000] {processor.py:154} INFO - Started process (PID=84627) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:54:04.852+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:54:04.853+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:54:04.852+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:54:04.856+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:54:04.855+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:54:04.856+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:54:04.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.016 seconds
[2025-05-06T18:54:35.531+0000] {processor.py:154} INFO - Started process (PID=84693) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:54:35.532+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:54:35.532+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:54:35.532+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:54:35.534+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:54:35.533+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:54:35.534+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:54:35.544+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:55:06.245+0000] {processor.py:154} INFO - Started process (PID=84759) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:06.246+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:06.246+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:06.246+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:06.248+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:06.248+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:06.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:06.259+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.015 seconds
[2025-05-06T18:55:30.171+0000] {processor.py:154} INFO - Started process (PID=84818) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:30.171+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:30.172+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:30.172+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:30.174+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:30.173+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:30.174+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:30.182+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
[2025-05-06T18:55:33.193+0000] {processor.py:154} INFO - Started process (PID=84819) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:33.194+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:33.194+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:33.194+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:33.197+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:33.196+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 13
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:33.197+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:33.210+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.020 seconds
[2025-05-06T18:55:36.236+0000] {processor.py:154} INFO - Started process (PID=84820) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:36.236+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:36.237+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:36.237+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:36.240+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:36.239+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 14
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:36.241+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:36.253+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.020 seconds
[2025-05-06T18:55:37.273+0000] {processor.py:154} INFO - Started process (PID=84821) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:37.273+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:37.274+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:37.274+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:37.276+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:37.275+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 14
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:37.276+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:37.288+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.018 seconds
[2025-05-06T18:55:40.116+0000] {processor.py:154} INFO - Started process (PID=84855) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:40.116+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:40.117+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:40.117+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:40.120+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:40.119+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 14
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:40.122+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:40.130+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.016 seconds
[2025-05-06T18:55:44.569+0000] {processor.py:154} INFO - Started process (PID=84868) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:44.570+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:44.570+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:44.570+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:44.572+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:44.572+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 14
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:44.572+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:44.580+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
[2025-05-06T18:55:48.611+0000] {processor.py:154} INFO - Started process (PID=84878) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:48.612+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:48.613+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:48.612+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:48.615+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:48.614+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 14
    )
    ^
SyntaxError: invalid syntax
[2025-05-06T18:55:48.615+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:48.623+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
[2025-05-06T18:55:53.668+0000] {processor.py:154} INFO - Started process (PID=84879) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:53.669+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:55:53.669+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:53.669+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:53.671+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:55:53.671+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 15
    
    ^
SyntaxError: unexpected EOF while parsing
[2025-05-06T18:55:53.671+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:55:53.682+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.015 seconds
[2025-05-06T18:56:01.753+0000] {processor.py:154} INFO - Started process (PID=84891) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:01.755+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:01.755+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:01.755+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:01.757+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:01.757+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 15
    
    ^
SyntaxError: unexpected EOF while parsing
[2025-05-06T18:56:01.757+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:01.766+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.015 seconds
[2025-05-06T18:56:03.776+0000] {processor.py:154} INFO - Started process (PID=84892) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:03.776+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:03.777+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:03.777+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:03.779+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:03.778+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 16
    
    ^
SyntaxError: unexpected EOF while parsing
[2025-05-06T18:56:03.779+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:03.788+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
[2025-05-06T18:56:06.818+0000] {processor.py:154} INFO - Started process (PID=84893) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:06.819+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:06.819+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:06.819+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:06.821+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:06.820+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 17
    
    ^
SyntaxError: unexpected EOF while parsing
[2025-05-06T18:56:06.821+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:06.832+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.015 seconds
[2025-05-06T18:56:14.161+0000] {processor.py:154} INFO - Started process (PID=84939) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:14.161+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:14.162+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:14.162+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:14.165+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:14.164+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 17
    def update_dataset()
                       ^
SyntaxError: invalid syntax
[2025-05-06T18:56:14.165+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:14.178+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.019 seconds
[2025-05-06T18:56:16.187+0000] {processor.py:154} INFO - Started process (PID=84940) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:16.187+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:16.188+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:16.188+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:16.191+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:16.190+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    
    ^
SyntaxError: unexpected EOF while parsing
[2025-05-06T18:56:16.191+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:16.202+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.019 seconds
[2025-05-06T18:56:20.231+0000] {processor.py:154} INFO - Started process (PID=84950) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:20.232+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:20.232+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:20.232+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:20.234+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:20.233+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open()
              ^
SyntaxError: invalid syntax
[2025-05-06T18:56:20.234+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:20.243+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:56:25.291+0000] {processor.py:154} INFO - Started process (PID=84951) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:25.292+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:25.292+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:25.292+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:25.294+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:25.293+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open(file.ur)
                     ^
SyntaxError: invalid syntax
[2025-05-06T18:56:25.294+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:25.303+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:56:26.584+0000] {processor.py:154} INFO - Started process (PID=84954) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:26.584+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:26.584+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:26.584+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:26.586+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:26.585+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open(file.uri, )
                        ^
SyntaxError: invalid syntax
[2025-05-06T18:56:26.586+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:26.595+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
[2025-05-06T18:56:30.622+0000] {processor.py:154} INFO - Started process (PID=84962) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:30.622+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:30.622+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:30.622+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:30.624+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:30.624+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open(file.uri, "")
                          ^
SyntaxError: invalid syntax
[2025-05-06T18:56:30.624+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:30.634+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:56:34.664+0000] {processor.py:154} INFO - Started process (PID=84965) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:34.664+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:34.664+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:34.664+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:34.666+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:34.666+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open(file.uri, "a")
                           ^
SyntaxError: invalid syntax
[2025-05-06T18:56:34.666+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:34.676+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:56:35.671+0000] {processor.py:154} INFO - Started process (PID=84966) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:35.672+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:35.672+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:35.672+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:35.674+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:35.673+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open(file.uri, "a+")
                            ^
SyntaxError: invalid syntax
[2025-05-06T18:56:35.674+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:35.684+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:56:44.224+0000] {processor.py:154} INFO - Started process (PID=85012) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:44.225+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:44.226+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:44.226+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:44.228+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:44.228+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 18
    with open(file.uri, "a+") as f
                                 ^
SyntaxError: invalid syntax
[2025-05-06T18:56:44.229+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:44.244+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.023 seconds
[2025-05-06T18:56:45.270+0000] {processor.py:154} INFO - Started process (PID=85013) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:45.271+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:45.271+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:45.271+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:45.274+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:45.273+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 19
    
    ^
SyntaxError: unexpected EOF while parsing
[2025-05-06T18:56:45.275+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:45.289+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.023 seconds
[2025-05-06T18:56:48.294+0000] {processor.py:154} INFO - Started process (PID=85014) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:48.295+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:48.295+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:48.295+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:48.299+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:48.298+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:56:48.299+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:48.309+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.017 seconds
[2025-05-06T18:56:49.314+0000] {processor.py:154} INFO - Started process (PID=85015) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:49.315+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:49.315+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:49.315+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:49.321+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:49.320+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:56:49.321+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:49.335+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.023 seconds
[2025-05-06T18:56:59.447+0000] {processor.py:154} INFO - Started process (PID=85027) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:59.448+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:56:59.449+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:59.449+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:59.454+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:56:59.453+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:56:59.454+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:56:59.465+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.021 seconds
[2025-05-06T18:57:07.540+0000] {processor.py:154} INFO - Started process (PID=85037) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:07.541+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:07.541+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:07.541+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:07.544+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:07.544+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:07.544+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:07.553+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:57:14.880+0000] {processor.py:154} INFO - Started process (PID=85083) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:14.881+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:14.881+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:14.881+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:14.884+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:14.883+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:14.884+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:14.892+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
[2025-05-06T18:57:30.038+0000] {processor.py:154} INFO - Started process (PID=85094) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:30.039+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:30.040+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:30.040+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:30.045+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:30.044+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:30.046+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:30.059+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.023 seconds
[2025-05-06T18:57:36.105+0000] {processor.py:154} INFO - Started process (PID=85104) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:36.105+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:36.106+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:36.106+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:36.110+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:36.109+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:36.110+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:36.124+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.022 seconds
[2025-05-06T18:57:39.151+0000] {processor.py:154} INFO - Started process (PID=85105) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:39.152+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:39.152+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:39.152+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:39.160+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:39.159+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:39.160+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:39.171+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.023 seconds
[2025-05-06T18:57:42.727+0000] {processor.py:154} INFO - Started process (PID=85122) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:42.730+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:42.731+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:42.731+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:42.735+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:42.734+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 16
    @task(outlets=)
                  ^
SyntaxError: invalid syntax
[2025-05-06T18:57:42.735+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:42.742+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.017 seconds
[2025-05-06T18:57:44.460+0000] {processor.py:154} INFO - Started process (PID=85143) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:44.461+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:44.461+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:44.461+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:44.465+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:44.464+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:44.465+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:44.476+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.018 seconds
[2025-05-06T18:57:49.517+0000] {processor.py:154} INFO - Started process (PID=85153) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:49.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:49.518+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:49.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:49.521+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:49.520+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:49.521+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:49.529+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:57:51.542+0000] {processor.py:154} INFO - Started process (PID=85154) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:51.542+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:57:51.543+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:51.543+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:51.546+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:57:51.545+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:57:51.546+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:57:51.554+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.014 seconds
[2025-05-06T18:58:22.127+0000] {processor.py:154} INFO - Started process (PID=85220) to work on /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:58:22.128+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/dataset_management_producet.py for tasks to queue
[2025-05-06T18:58:22.128+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:58:22.128+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:58:22.131+0000] {logging_mixin.py:120} INFO - [2025-05-06T18:58:22.130+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/dataset_management_producet.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dataset_management_producet.py", line 2, in <module>
    from airflow.decorator import task
ModuleNotFoundError: No module named 'airflow.decorator'
[2025-05-06T18:58:22.131+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/dataset_management_producet.py
[2025-05-06T18:58:22.139+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/dataset_management_producet.py took 0.013 seconds
